/*
package com.hyphenate.easeui.model;

import com.hyphenate.easeui.R;
import com.hyphenate.easeui.domain.EaseEmojicon;
import com.hyphenate.easeui.domain.EaseEmojicon.Type;
import com.hyphenate.easeui.utils.EaseSmileUtils;

public class EaseDefaultEmojiconDatas {
    
    private static String[] emojis = new String[]{
        EaseSmileUtils.EE_1,
        EaseSmileUtils.EE_2,
        EaseSmileUtils.EE_3,
        EaseSmileUtils.EE_4,
        EaseSmileUtils.EE_5,
        EaseSmileUtils.EE_6,
        EaseSmileUtils.EE_7,
        EaseSmileUtils.EE_8,
        EaseSmileUtils.EE_9,
        EaseSmileUtils.EE_10,
        EaseSmileUtils.EE_11,
        EaseSmileUtils.EE_12,
        EaseSmileUtils.EE_13,
        EaseSmileUtils.EE_14,
        EaseSmileUtils.EE_15,
        EaseSmileUtils.EE_16,
        EaseSmileUtils.EE_17,
        EaseSmileUtils.EE_18,
        EaseSmileUtils.EE_19,
        EaseSmileUtils.EE_20,
        EaseSmileUtils.EE_21,
        EaseSmileUtils.EE_22,
        EaseSmileUtils.EE_23,
        EaseSmileUtils.EE_24,
        EaseSmileUtils.EE_25,
        EaseSmileUtils.EE_26,
        EaseSmileUtils.EE_27,
        EaseSmileUtils.EE_28,
        EaseSmileUtils.EE_29,
        EaseSmileUtils.EE_30,
        EaseSmileUtils.EE_31,
        EaseSmileUtils.EE_32,
        EaseSmileUtils.EE_33,
        EaseSmileUtils.EE_34,
        EaseSmileUtils.EE_35,
       
    };
    
    private static int[] icons = new int[]{
        R.drawable.ee_1,  
        R.drawable.ee_2,  
        R.drawable.ee_3,  
        R.drawable.ee_4,  
        R.drawable.ee_5,  
        R.drawable.ee_6,  
        R.drawable.ee_7,  
        R.drawable.ee_8,  
        R.drawable.ee_9,  
        R.drawable.ee_10,  
        R.drawable.ee_11,  
        R.drawable.ee_12,  
        R.drawable.ee_13,  
        R.drawable.ee_14,  
        R.drawable.ee_15,  
        R.drawable.ee_16,  
        R.drawable.ee_17,  
        R.drawable.ee_18,  
        R.drawable.ee_19,
        R.drawable.ee_20,  
        R.drawable.ee_21,  
        R.drawable.ee_22,  
        R.drawable.ee_23,  
        R.drawable.ee_24,  
        R.drawable.ee_25,  
        R.drawable.ee_26,  
        R.drawable.ee_27,  
        R.drawable.ee_28,  
        R.drawable.ee_29,  
        R.drawable.ee_30,  
        R.drawable.ee_31,  
        R.drawable.ee_32,  
        R.drawable.ee_33,  
        R.drawable.ee_34,  
        R.drawable.ee_35,  
    };
    
    
    private static final EaseEmojicon[] DATA = createData();
    
    private static EaseEmojicon[] createData(){
        EaseEmojicon[] datas = new EaseEmojicon[icons.length];
        for(int i = 0; i < icons.length; i++){
            datas[i] = new EaseEmojicon(icons[i], emojis[i], Type.NORMAL);
        }
        return datas;
    }
    
    public static EaseEmojicon[] getData(){
        return DATA;
    }
}
*/
package com.hyphenate.easeui.model;

import com.hyphenate.easeui.R;
import com.hyphenate.easeui.domain.EaseEmojicon;
import com.hyphenate.easeui.domain.EaseEmojicon.Type;
import com.hyphenate.easeui.utils.EaseSmileUtils;

public class EaseDefaultEmojiconDatas {

    private static String[] emojis = new String[]{
            "[emoji001]",
            "[emoji002]",
            "[emoji003]",
            "[emoji004]",
            "[emoji005]",
            "[emoji006]",
            "[emoji007]",
            "[emoji008]",
            "[emoji009]",
            "[emoji010]",
            "[emoji011]",
            "[emoji012]",
            "[emoji013]",
            "[emoji014]",
            "[emoji015]",
            "[emoji016]",
            "[emoji017]",
            "[emoji018]",
            "[emoji019]",
            "[emoji020]",
            "[emoji021]",
            "[emoji022]",
            "[emoji023]",
            "[emoji024]",
            "[emoji025]",
            "[emoji026]",
            "[emoji027]",
            "[emoji028]",
            "[emoji029]",
            "[emoji030]",
            "[emoji031]",
            "[emoji032]",
            "[emoji033]",
            "[emoji034]",
            "[emoji035]",
            "[emoji036]",
            "[emoji037]",
            "[emoji038]",
            "[emoji039]",
            "[emoji040]",
            "[emoji041]",
            "[emoji042]",
            "[emoji043]",
            "[emoji044]",
            "[emoji045]",
            "[emoji046]",
            "[emoji047]",
            "[emoji048]",
            "[emoji049]",
            "[emoji050]",
            "[emoji051]",
            "[emoji052]",
            "[emoji053]",
            "[emoji054]",
            "[emoji055]",
            "[emoji056]",
            "[emoji057]",
            "[emoji058]",
            "[emoji059]",
            "[emoji060]",
            "[emoji061]",
            "[emoji062]",
            "[emoji063]",
            "[emoji064]",
            "[emoji065]",
            "[emoji066]",
            "[emoji067]",
            "[emoji068]",
            "[emoji069]",
            "[emoji070]",
            "[emoji071]",
            "[emoji072]",
            "[emoji073]",
            "[emoji074]",
            "[emoji075]",
            "[emoji076]",
            "[emoji077]",
            "[emoji078]",
            "[emoji079]",
            "[emoji080]",
            "[emoji081]",
            "[emoji082]",
            "[emoji083]",
            "[emoji084]",
            "[emoji085]",
            "[emoji086]",
            "[emoji087]",
            "[emoji088]",
            "[emoji089]",
            "[emoji090]",
            "[emoji091]",
            "[emoji092]",
            "[emoji093]",
            "[emoji094]",
            "[emoji095]",
            "[emoji096]",
            "[emoji097]",
            "[emoji098]",
            "[emoji099]",
            "[emoji100]",
            "[emoji101]",
            "[emoji102]",
            "[emoji103]",
            "[emoji104]",
            "[emoji105]",
            "[emoji106]",
            "[emoji107]",

    };

    private static int[] icons = new int[]{
            R.drawable.e1f600,
            R.drawable.e1f601,
            R.drawable.e1f602,
            R.drawable.e1f923,
            R.drawable.e1f924,
            R.drawable.e1f603,
            R.drawable.e1f604,
            R.drawable.e1f605,
            R.drawable.e1f606,
            R.drawable.e1f607,
            R.drawable.e1f608,
            R.drawable.e1f609,
            R.drawable.e1f60a,
            R.drawable.e1f60b,
            R.drawable.e1f60c,
            R.drawable.e1f60d,
            R.drawable.e1f60e,
            R.drawable.e1f60f,
            R.drawable.e1f610,
            R.drawable.e1f611,
            R.drawable.e1f641,
            R.drawable.e1f642,
            R.drawable.e1f643,
            R.drawable.e1f644,
            R.drawable.e1f612,
            R.drawable.e1f613,
            R.drawable.e1f614,
            R.drawable.e1f615,
            R.drawable.e1f616,
            R.drawable.e1f617,
            R.drawable.e1f618,
            R.drawable.e1f619,
            R.drawable.e1f61a,
            R.drawable.e1f61b,
            R.drawable.e1f61c,
            R.drawable.e1f61d,
            R.drawable.e1f61e,
            R.drawable.e1f61f,
            R.drawable.e1f620,
            R.drawable.e1f621,
            R.drawable.e1f622,
            R.drawable.e1f623,
            R.drawable.e1f624,
            R.drawable.e1f625,
            R.drawable.e1f626,
            R.drawable.e1f627,
            R.drawable.e1f628,
            R.drawable.e1f629,
            R.drawable.e1f62a,
            R.drawable.e1f62b,
            R.drawable.e1f62c,
            R.drawable.e1f62d,
            R.drawable.e1f62e,
            R.drawable.e1f62f,
            R.drawable.e1f630,
            R.drawable.e1f631,
            R.drawable.e1f632,
            R.drawable.e1f633,
            R.drawable.e1f634,
            R.drawable.e1f635,
            R.drawable.e1f636,
            R.drawable.e1f925,
            R.drawable.e2639,
            R.drawable.e1f927,
            R.drawable.e1f637,
            R.drawable.e1f910,
            R.drawable.e1f911,
            R.drawable.e1f912,
            R.drawable.e1f913,
            R.drawable.e1f914,
            R.drawable.e1f915,
            R.drawable.e1f638,
            R.drawable.e1f639,
            R.drawable.e1f63a,
            R.drawable.e1f63b,
            R.drawable.e1f63c,
            R.drawable.e1f63d,
            R.drawable.e1f63e,
            R.drawable.e1f63f,
            R.drawable.e1f640,
            R.drawable.e1f648,
            R.drawable.e1f649,
            R.drawable.e1f64a,
            R.drawable.e1f916,
            R.drawable.e1f917,
            R.drawable.e1f920,
            R.drawable.e1f921,
            R.drawable.e1f922,
            R.drawable.e1f918_1f3fb,
            R.drawable.e1f44a_1f3fb,
            R.drawable.e1f44b_1f3fb,
            R.drawable.e1f44c_1f3fb,
            R.drawable.e1f44d_1f3fb,
            R.drawable.e1f44e_1f3fb,
            R.drawable.e1f44f_1f3fb,
            R.drawable.e1f4aa_1f3fb,
            R.drawable.e1f595_1f3fb,
            R.drawable.e1f645_1f3fb_2640,
            R.drawable.e1f645_1f3fb_2642,
            R.drawable.e1f646_1f3fb_2640,
            R.drawable.e1f646_1f3fb_2642,
            R.drawable.e1f647_1f3fb_2640,
            R.drawable.e1f647_1f3fb_2642,
            R.drawable.e1f926_1f3fb_2640,
            R.drawable.e1f926_1f3fb_2642,
            R.drawable.e1f937_1f3fb_2640,
            R.drawable.e1f937_1f3fb_2642,

    };


    private static final EaseEmojicon[] DATA = createData();

    private static EaseEmojicon[] createData(){
        EaseEmojicon[] datas = new EaseEmojicon[icons.length];
        for(int i = 0; i < icons.length; i++){
            datas[i] = new EaseEmojicon(icons[i], emojis[i], Type.NORMAL);
        }
        return datas;
    }

    public static EaseEmojicon[] getData(){
        return DATA;
    }
}
